import { RankData } from '../viewmodel/RankData'

export { rankData1 }

const rankData1: RankData[] = [
  new RankData('1', $r('app.string.fruit_apple'), '12080'),
  new RankData('2', $r('app.string.fruit_grapes'), '10320'),
  new RankData('3', $r('app.string.fruit_watermelon'), '9801'),
  new RankData('4', $r('app.string.fruit_banana'), '8431'),
  new RankData('5', $r('app.string.fruit_pineapple'), '7546'),
  new RankData('6', $r('app.string.fruit_durian'), '7431'),
  new RankData('7', $r('app.string.fruit_red_grape'), '7187'),
  new RankData('8', $r('app.string.fruit_pears'), '7003'),
  new RankData('9', $r('app.string.fruit_carambola'), '6794'),
  new RankData('10', $r('app.string.fruit_guava'), '6721')
];